apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-1
spec:
  ports:
  - port: 9092
    name: internal-port
    protocol: TCP
  - port: 9093
    name: external-port
    protocol: TCP
  selector:
    app: kafka-1
  type: LoadBalancer
